name: Cypress Tests
on:
  workflow_dispatch:
    inputs:
      targer_os:
        description: 'test'
        required: false
        default: 'all'

jobs:
  job-all:
    runs-on: media_processor_auto_pr_osx_j
    needs: [cypress-run-osx, cypress-run-windows]
    steps:
    - name: check job results
      shell: bash
      run: |
          echo cypress-run-osx=${{ needs.cypress-run-osx.result }} cypress-run-windows=${{ needs.cypress-run-windows.result }} 
  cypress-run-osx:
    runs-on: media_processor_auto_pr_osx_j
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build:dev
          start: npm run dev 
          wait-on: 'http://localhost:3000'
          browser: chrome
          record: true
          spec: "cypress/integration/osx/*.js"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  cypress-run-windows:
    runs-on: media_processor_auto_pr_windows_aws1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build:dev
          start: npm run dev 
          wait-on: 'http://localhost:3000'
          browser: chrome
          record: true
          spec: "cypress/integration/windows/*.js"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
